version: "3.8"
services:
  tailscale:
    image: docker.io/tailscale/tailscale
    volumes:
      - tailscale-data:/var/lib/tailscale
    devices:
      - /dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: .env
  hubitat_exporter:
    image: ghcr.io/jaksi/hubitat_exporter
    environment:
      LISTEN_ADDRESS: ":1123"
      HUBITAT_ADDRESS: "http://192.168.1.4"
    env_file: .env
  prometheus:
    image: docker.io/prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  grafana:
    image: docker.io/grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  caddy:
    build: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    env_file: .env
volumes:
  tailscale-data:
  prometheus-data:
  grafana-data:
  caddy-data:
  caddy-config:
