#!/bin/bash
set -euo pipefail

cd /opt/server

echo Updating repo
git pull

echo Disabling and stopping systemd units
systemctl list-units 'docker-compose*' --no-legend | awk '{print $1}' | xargs -r systemctl disable --now

echo Removing systemd units
rm /etc/systemd/system/docker-compose* || true

echo Resetting failed systemd units
systemctl reset-failed

echo Stopping docker containers
docker-compose down --remove-orphans -t 60

echo Removing docker containers
docker-compose rm -fv

echo Pruning docker images
docker image prune -fa

echo Pruning docker networks
docker network prune -f

echo Installing systemd units
cp systemd/* /etc/systemd/system/

echo Reloading systemd
systemctl daemon-reload

echo Enabling and starting systemd services
yq e '.services | keys | .[] | select(. != "backup")' docker-compose.yml | xargs -i systemctl enable --now docker-compose@{}.service

echo Enabling the backup systemd timer
systemctl enable --now docker-compose-backup.timer

while true; do
  clear
  systemctl list-units 'docker-compose*'
  sleep 1
done
